// <auto-generated />
namespace TinderServer2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class user_event_relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_event_relation));
        
        string IMigrationMetadata.Id
        {
            get { return "201706251326567_user_event_relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
