// <auto-generated />
namespace TinderServer2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class float_gps_to_double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(float_gps_to_double));
        
        string IMigrationMetadata.Id
        {
            get { return "201705021849389_float_gps_to_double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
