// <auto-generated />
namespace TinderServer2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class imageeventrelation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imageeventrelation));
        
        string IMigrationMetadata.Id
        {
            get { return "201706171919055_image-event-relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
