// <auto-generated />
namespace TinderServer2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_db_setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_db_setup));
        
        string IMigrationMetadata.Id
        {
            get { return "201705011117119_initial_db_setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
